import 'dart:async';
import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../app/constants.dart';
import '../../shared/models/song.dart';
import '../../shared/models/playlist.dart';
import '../../shared/models/album.dart';
import '../../shared/models/artist.dart';
import '../audio/audio_manager.dart';
import '../data/mock_catalog.dart';
import '../network/network_state.dart';
import '../storage/local_storage.dart';

enum HomeSectionType {
  playlists,
  albums,
  artists,
  songs,
}

class AiSpotlightData {
  final String title;
  final String rationale;
  final String badge;
  final Song featuredSong;
  final List<Song> playlist;

  AiSpotlightData({
    required this.title,
    required this.rationale,
    required this.badge,
    required this.featuredSong,
    required this.playlist,
  });
}

/// A dynamically computed Home Section (shelf) generated by the recommendation algorithm
class HomeSection {
  final String id;
  final String title;
  final String? subtitle;
  final String? badge;
  final HomeSectionType type;
  final List<Playlist>? playlists;
  final List<Album>? albums;
  final List<Artist>? artists;
  final List<Song>? songs;

  HomeSection({
    required this.id,
    required this.title,
    this.subtitle,
    this.badge,
    required this.type,
    this.playlists,
    this.albums,
    this.artists,
    this.songs,
  });
}

/// Fully Dynamic Home Feed computed from user behavior & Gemini AI trend analysis
class HomeFeedData {
  final String greeting;
  final List<Song> quickPlaySongs;
  final AiSpotlightData? aiSpotlight;
  final List<HomeSection> sections;

  HomeFeedData({
    required this.greeting,
    required this.quickPlaySongs,
    this.aiSpotlight,
    required this.sections,
  });
}

final recommendationServiceProvider = Provider<RecommendationService>((ref) {
  return RecommendationService();
});

final homeFeedProvider = StateNotifierProvider<HomeFeedNotifier, AsyncValue<HomeFeedData>>((ref) {
  final service = ref.watch(recommendationServiceProvider);
  return HomeFeedNotifier(service, ref);
});

class HomeFeedNotifier extends StateNotifier<AsyncValue<HomeFeedData>> {
  final RecommendationService _service;
  final Ref _ref;
  DateTime? _lastGeneratedTime;
  Timer? _dailyCycleTimer;

  HomeFeedNotifier(this._service, this._ref) : super(const AsyncValue.loading()) {
    refreshFeed();

    // 1. Reactive trigger: Automatically re-generate algorithm when user plays any song
    _ref.listen(playerStateProvider.select((s) => s.currentSong?.id), (previous, next) {
      if (next != null && next != previous) {
        refreshFeed();
      }
    });



    // 3. Network reconnection trigger: When internet comes back ON, immediately refresh daily trend data
    _ref.listen(networkStatusProvider, (previous, next) {
      if (next == NetworkStatus.online && previous != NetworkStatus.online) {
        refreshFeed();
      }
    });

    // 4. Daily 5:30 AM IST timer check (runs every minute to catch 5:30 AM IST boundary while app is open)
    _dailyCycleTimer = Timer.periodic(const Duration(minutes: 1), (_) {
      final mostRecent530Am = _getMostRecent530AmIst();
      if (_lastGeneratedTime != null && _lastGeneratedTime!.isBefore(mostRecent530Am)) {
        refreshFeed();
      }
    });
  }

  /// Calculates the most recent 5:30 AM IST timestamp (UTC 00:00)
  static DateTime _getMostRecent530AmIst() {
    final nowUtc = DateTime.now().toUtc();
    final today530AmIst = DateTime.utc(nowUtc.year, nowUtc.month, nowUtc.day, 0, 0, 0);
    if (nowUtc.isBefore(today530AmIst)) {
      return today530AmIst.subtract(const Duration(days: 1));
    }
    return today530AmIst;
  }

  Future<void> refreshFeed() async {
    try {
      final currentSong = _ref.read(playerStateProvider).currentSong;
      final feed = await _service.generateHomeFeed(currentSong: currentSong);
      _lastGeneratedTime = DateTime.now().toUtc();
      state = AsyncValue.data(feed);
    } catch (e) {
      final currentSong = _ref.read(playerStateProvider).currentSong;
      final fallback = _service.generateLocalAlgorithmicFeed(currentSong: currentSong);
      _lastGeneratedTime = DateTime.now().toUtc();
      state = AsyncValue.data(fallback);
    }
  }

  @override
  void dispose() {
    _dailyCycleTimer?.cancel();
    super.dispose();
  }
}

class RecommendationService {
  final Dio _dio = Dio(BaseOptions(
    connectTimeout: const Duration(milliseconds: 1200),
    receiveTimeout: const Duration(milliseconds: 1200),
  ));

  /// Generates the dynamic algorithmic Home Feed with Gemini AI trend analysis
  Future<HomeFeedData> generateHomeFeed({Song? currentSong}) async {
    // 1. Fetch latest songs from PostgreSQL DB (paginated 100 tracks)
    try {
      final candidateEndpoints = [
        '${AppConstants.defaultApiBaseUrl}/songs?limit=100',
        ...AppConstants.fallbackApiBaseUrls.map((u) => '$u/songs?limit=100'),
      ];

      for (final endpoint in candidateEndpoints) {
        try {
          final songsRes = await _dio.get(endpoint);
          if (songsRes.statusCode == 200 && songsRes.data != null) {
            final data = songsRes.data;
            final list = (data is Map ? (data['data'] ?? data['songs']) : data) as List<dynamic>?;
            if (list != null && list.isNotEmpty) {
              for (final item in list) {
                final songId = (item['id'] ?? '').toString();
                if (songId.isNotEmpty) {
                  final newSong = Song(
                    id: songId,
                    title: (item['title'] ?? 'Untitled Track').toString(),
                    artist: (item['artistName'] ?? item['artist']?['name'] ?? item['artist'] ?? 'Unknown Artist').toString(),
                    album: (item['albumName'] ?? item['album']?['title'] ?? item['album'] ?? 'Single').toString(),
                    movieName: item['movieName']?.toString(),
                    artworkUrl: (item['artworkUrl'] ?? item['artwork'] ?? '').toString(),
                    audioUrl: (item['audioUrl'] ?? '').toString(),
                    duration: (item['duration'] as num?)?.toInt() ?? 180,
                    genre: (item['genre'] ?? 'Music').toString(),
                    language: (item['language'] ?? 'Tamil').toString(),
                    lyrics: (item['lyrics'] is List) ? List<String>.from(item['lyrics']) : [],
                  );
                  MockMusicCatalog.syncSong(newSong);
                }
              }
              break;
            }
          }
        } catch (_) {}
      }
    } catch (_) {}

    final localFeed = generateLocalAlgorithmicFeed(currentSong: currentSong);

    try {
      final res = await _dio.get(
        '${AppConstants.defaultApiBaseUrl}/recommendations/trending',
      );

      if (res.statusCode == 200 && res.data != null) {
        final data = res.data as Map<String, dynamic>;
        final spotlight = data['dailySpotlight'] as Map<String, dynamic>?;
        if (spotlight != null && localFeed.aiSpotlight != null) {
          final updatedSpotlight = AiSpotlightData(
            title: spotlight['title'] ?? localFeed.aiSpotlight!.title,
            rationale: spotlight['rationale'] ?? localFeed.aiSpotlight!.rationale,
            badge: spotlight['badge'] ?? localFeed.aiSpotlight!.badge,
            featuredSong: localFeed.aiSpotlight!.featuredSong,
            playlist: localFeed.aiSpotlight!.playlist,
          );
          return HomeFeedData(
            greeting: localFeed.greeting,
            quickPlaySongs: localFeed.quickPlaySongs,
            aiSpotlight: updatedSpotlight,
            sections: localFeed.sections,
          );
        }
      }
    } catch (_) {
      // Offline fallback
    }

    return localFeed;
  }

  /// 100% Dynamic Spotify & Gemini AI Recommendation Engine
  HomeFeedData generateLocalAlgorithmicFeed({Song? currentSong}) {
    final allSongs = MockMusicCatalog.allSongs;
    final recentlyPlayed = LocalStorageService.getRecentlyPlayed();
    final likedSongs = LocalStorageService.getLikedSongs();

    final hour = DateTime.now().hour;
    final String greeting;
    if (hour < 12) {
      greeting = 'Good morning';
    } else if (hour < 17) {
      greeting = 'Good afternoon';
    } else {
      greeting = 'Good evening';
    }

    // 1. Live User Affinity Scoring Matrix
    final Map<String, int> artistAffinity = {};

    // A. Currently Playing Song (+12 immediate focus)
    if (currentSong != null) {
      final currentArtist = MockMusicCatalog.normalizeArtistName(currentSong.artist);
      artistAffinity[currentArtist] = (artistAffinity[currentArtist] ?? 0) + 12;
    }

    // B. Recently Played Songs (+5 for first 10, +2 for older)
    for (int i = 0; i < recentlyPlayed.length; i++) {
      final s = recentlyPlayed[i];
      final a = MockMusicCatalog.normalizeArtistName(s.artist);
      final weight = i < 10 ? 5 : 2;
      artistAffinity[a] = (artistAffinity[a] ?? 0) + weight;
    }

    // C. Liked Songs (+6 for each liked song)
    for (final s in likedSongs) {
      final a = MockMusicCatalog.normalizeArtistName(s.artist);
      artistAffinity[a] = (artistAffinity[a] ?? 0) + 6;
    }

    // Sort all artists by live user affinity
    final sortedAffinity = artistAffinity.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    // Dynamic Top Artists
    final top1 = sortedAffinity.isNotEmpty ? sortedAffinity[0].key : 'Anirudh Ravichander';
    final top2 = sortedAffinity.length > 1 ? sortedAffinity[1].key : 'A.R. Rahman';
    final top3 = sortedAffinity.length > 2 ? sortedAffinity[2].key : 'Yuvan Shankar Raja';

    // 2. Dynamic Quick-Play 6-Pack (Instantly updates on every track played/liked)
    final Set<String> quickPlayIds = {};
    final List<Song> quickPlay = [];

    if (currentSong != null) {
      quickPlay.add(currentSong);
      quickPlayIds.add(currentSong.id);
    }
    for (final s in recentlyPlayed) {
      if (quickPlay.length < 4 && !quickPlayIds.contains(s.id)) {
        quickPlay.add(s);
        quickPlayIds.add(s.id);
      }
    }
    for (final s in likedSongs) {
      if (quickPlay.length < 6 && !quickPlayIds.contains(s.id)) {
        quickPlay.add(s);
        quickPlayIds.add(s.id);
      }
    }
    for (final s in allSongs) {
      if (quickPlay.length < 6 && !quickPlayIds.contains(s.id)) {
        final a = MockMusicCatalog.normalizeArtistName(s.artist);
        if (a == top1 || a == top2) {
          quickPlay.add(s);
          quickPlayIds.add(s.id);
        }
      }
    }
    if (quickPlay.length < 6) {
      for (final s in allSongs) {
        if (quickPlay.length < 6 && !quickPlayIds.contains(s.id)) {
          quickPlay.add(s);
          quickPlayIds.add(s.id);
        }
      }
    }

    // 3. Gemini AI Live Tamil Trending Songs & Playlists Analysis
    final trendingSongs = List<Song>.from(allSongs);
    trendingSongs.sort((a, b) {
      final aTrendWeight = _getSongTrendWeight(a);
      final bTrendWeight = _getSongTrendWeight(b);
      return bTrendWeight.compareTo(aTrendWeight);
    });

    final massAnthems = allSongs.where((s) {
      final t = s.title.toLowerCase();
      final m = (s.movieName ?? s.album).toLowerCase();
      final g = s.genre.toLowerCase();
      return g.contains('dance') ||
          g.contains('hip-hop') ||
          t.contains('matta') ||
          t.contains('spark') ||
          t.contains('hukum') ||
          t.contains('badass') ||
          t.contains('naa ready') ||
          t.contains('jalabulajangu') ||
          t.contains('arabic kuthu') ||
          t.contains('aaluma') ||
          t.contains('marana') ||
          t.contains('whistle') ||
          t.contains('mass') ||
          t.contains('anthem') ||
          t.contains('theme') ||
          m.contains('goat') ||
          m.contains('leo') ||
          m.contains('jailer') ||
          m.contains('vettaiyan');
    }).take(20).toList();

    final chillMelodies = allSongs.where((s) {
      final t = s.title.toLowerCase();
      final a = s.artist.toLowerCase();
      return t.contains('love') ||
          t.contains('kadhal') ||
          t.contains('melody') ||
          t.contains('kanave') ||
          t.contains('uyire') ||
          t.contains('minnale') ||
          t.contains('nenj') ||
          t.contains('poo') ||
          t.contains('kadhale') ||
          a.contains('sid sriram') ||
          a.contains('pradeep kumar') ||
          a.contains('shreya ghoshal') ||
          a.contains('chinmayi') ||
          a.contains('haricharan') ||
          a.contains('shweta mohan');
    }).take(20).toList();

    final viralHits = trendingSongs.where((s) {
      final t = s.title.toLowerCase();
      final m = (s.movieName ?? s.album).toLowerCase();
      return m.contains('goat') ||
          m.contains('amaran') ||
          m.contains('vettaiyan') ||
          m.contains('leo') ||
          t.contains('katchi sera') ||
          t.contains('minnale') ||
          t.contains('spark') ||
          t.contains('matta');
    }).take(15).toList();

    // Curated Trending Playlists (Strictly matching titles)
    final trendingTamilPlaylists = [
      Playlist(
        id: 'trending_tamil_top_50',
        title: 'Trending Tamil Top 50',
        description: 'The hottest Tamil tracks trending today across India & global charts.',
        coverUrl: trendingSongs.isNotEmpty ? trendingSongs.first.artworkUrl : '',
        creator: 'Spotify',
        songs: trendingSongs.take(20).toList(),
      ),
      Playlist(
        id: 'hot_hits_tamil',
        title: 'Hot Hits Tamil',
        description: 'Catch the biggest viral blockbusters and fresh drops in Tamil cinema.',
        coverUrl: trendingSongs.length > 1 ? trendingSongs[1].artworkUrl : '',
        creator: 'Spotify',
        songs: trendingSongs.skip(3).take(15).toList(),
      ),
      if (massAnthems.isNotEmpty)
        Playlist(
          id: 'kollywood_mass_anthems',
          title: 'Kollywood Mass Anthems',
          description: 'High-octane theater celebration songs from Leo, GOAT, Jailer & Vettaiyan.',
          coverUrl: massAnthems.first.artworkUrl,
          creator: 'Spotify',
          songs: massAnthems,
        ),
      if (viralHits.isNotEmpty)
        Playlist(
          id: 'tamil_viral_hits',
          title: 'Tamil Viral Hits',
          description: 'The most viral tracks dominating streaming & social feeds.',
          coverUrl: viralHits.first.artworkUrl,
          creator: 'Spotify',
          songs: viralHits,
        ),
      if (chillMelodies.isNotEmpty)
        Playlist(
          id: 'tamil_acoustic_chill',
          title: 'Tamil Chill & Melodies',
          description: 'Soulful acoustic vocals and evergreen soothing melodies.',
          coverUrl: chillMelodies.first.artworkUrl,
          creator: 'Spotify',
          songs: chillMelodies,
        ),
    ];

    // 4. Dynamic Section: "Made For You" (Strictly ONLY songs by each specific artist)
    final mix1Songs = _getArtistMixTracks(allSongs, top1);
    final mix2Songs = _getArtistMixTracks(allSongs, top2);
    final mix3Songs = _getArtistMixTracks(allSongs, top3);

    final heardIds = {...recentlyPlayed.map((s) => s.id), ...likedSongs.map((s) => s.id)};
    final discoverSongs = allSongs.where((s) {
      if (heardIds.contains(s.id)) return false;
      return MockMusicCatalog.isSongByArtist(s, top1) ||
          MockMusicCatalog.isSongByArtist(s, top2) ||
          MockMusicCatalog.isSongByArtist(s, top3);
    }).take(20).toList();

    final madeForYouPlaylists = [
      if (mix1Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top1.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top1 Mix',
          description: 'The best of $top1, all in one place.',
          coverUrl: mix1Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix1Songs,
        ),
      if (mix2Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top2.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top2 Mix',
          description: 'The best of $top2, all in one place.',
          coverUrl: mix2Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix2Songs,
        ),
      if (mix3Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top3.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top3 Mix',
          description: 'The best of $top3, all in one place.',
          coverUrl: mix3Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix3Songs,
        ),
      if (discoverSongs.isNotEmpty)
        Playlist(
          id: 'discover_weekly',
          title: 'Discover Weekly',
          description: 'Your weekly mixtape of fresh tracks picked for you.',
          coverUrl: discoverSongs.first.artworkUrl,
          creator: 'Spotify',
          songs: discoverSongs,
        ),
    ];

    // 5. Dynamic Section: Time & Mood Shift Shelf (Strict thematic songs only)
    final String timeSectionTitle;
    final List<Playlist> timePlaylists;
    if (hour >= 5 && hour < 12) {
      timeSectionTitle = 'Morning Motivation';
      final morningMotivation = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return a.contains('anirudh') ||
            a.contains('santhosh') ||
            a.contains('hiphop') ||
            t.contains('arambam') ||
            t.contains('rise') ||
            t.contains('power') ||
            t.contains('badass') ||
            t.contains('energy');
      }).take(15).toList();

      final acousticMorning = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return t.contains('kadhal') ||
            t.contains('melody') ||
            t.contains('kanave') ||
            t.contains('poo') ||
            a.contains('sid sriram') ||
            a.contains('pradeep kumar');
      }).take(15).toList();

      timePlaylists = [
        if (morningMotivation.isNotEmpty)
          Playlist(
            id: 'morning_energy',
            title: 'Morning Motivation',
            description: 'Uplifting tracks to start your day with power.',
            coverUrl: morningMotivation.first.artworkUrl,
            creator: 'Spotify',
            songs: morningMotivation,
          ),
        if (acousticMorning.isNotEmpty)
          Playlist(
            id: 'acoustic_morning',
            title: 'Tamil Acoustic Starts',
            description: 'Soothing morning acoustic guitar and vocals.',
            coverUrl: acousticMorning.first.artworkUrl,
            creator: 'Spotify',
            songs: acousticMorning,
          ),
      ];
    } else if (hour >= 12 && hour < 17) {
      timeSectionTitle = 'Afternoon Beats';
      final partyHits = massAnthems.take(15).toList();
      final driveHits = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return a.contains('anirudh') ||
            a.contains('harris') ||
            a.contains('yuvan') ||
            t.contains('ride') ||
            t.contains('drive') ||
            t.contains('beat') ||
            t.contains('theme');
      }).take(15).toList();

      timePlaylists = [
        if (partyHits.isNotEmpty)
          Playlist(
            id: 'afternoon_flow',
            title: 'Afternoon High Energy',
            description: 'Mass beats and high-octane chartbusters.',
            coverUrl: partyHits.first.artworkUrl,
            creator: 'Spotify',
            songs: partyHits,
          ),
        if (driveHits.isNotEmpty)
          Playlist(
            id: 'kollywood_drive',
            title: 'Kollywood Drive Beats',
            description: 'The ultimate driving soundtrack for your afternoon.',
            coverUrl: driveHits.first.artworkUrl,
            creator: 'Spotify',
            songs: driveHits,
          ),
      ];
    } else if (hour >= 17 && hour < 22) {
      timeSectionTitle = 'Evening Melodies';
      final eveningUnwind = allSongs.where((s) {
        final a = MockMusicCatalog.normalizeArtistName(s.artist);
        return a == 'A.R. Rahman' || a == 'Harris Jayaraj' || a == 'Yuvan Shankar Raja';
      }).take(15).toList();

      final sunsetMelodies = chillMelodies.take(15).toList();

      timePlaylists = [
        if (eveningUnwind.isNotEmpty)
          Playlist(
            id: 'evening_unwind',
            title: 'Evening Unwind',
            description: 'Relax and groove with iconic melodies & timeless hits.',
            coverUrl: eveningUnwind.first.artworkUrl,
            creator: 'Spotify',
            songs: eveningUnwind,
          ),
        if (sunsetMelodies.isNotEmpty)
          Playlist(
            id: 'sunset_melodies',
            title: 'Sunset Melodies',
            description: 'Golden hour love songs and acoustic harmonies.',
            coverUrl: sunsetMelodies.first.artworkUrl,
            creator: 'Spotify',
            songs: sunsetMelodies,
          ),
      ];
    } else {
      timeSectionTitle = 'Late Night Chill';
      final lateNightMelodies = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return t.contains('melody') ||
            t.contains('love') ||
            t.contains('nenj') ||
            t.contains('uyire') ||
            a.contains('pradeep kumar') ||
            a.contains('shreya ghoshal') ||
            a.contains('sid sriram');
      }).take(15).toList();

      final midnightNostalgia = allSongs.where((s) {
        final a = MockMusicCatalog.normalizeArtistName(s.artist);
        return a == 'Yuvan Shankar Raja' || a == 'A.R. Rahman' || a == 'Ilaiyaraaja';
      }).take(15).toList();

      timePlaylists = [
        if (lateNightMelodies.isNotEmpty)
          Playlist(
            id: 'late_night_chill',
            title: 'Late Night Chill',
            description: 'Soft strings, soul vocals & soothing midnight vibes.',
            coverUrl: lateNightMelodies.first.artworkUrl,
            creator: 'Spotify',
            songs: lateNightMelodies,
          ),
        if (midnightNostalgia.isNotEmpty)
          Playlist(
            id: 'midnight_nostalgia',
            title: 'Midnight Nostalgia',
            description: 'Classic evergreen night melodies by Yuvan & Rahman.',
            coverUrl: midnightNostalgia.first.artworkUrl,
            creator: 'Spotify',
            songs: midnightNostalgia,
          ),
      ];
    }

    // 6. Dynamic Album Ranking (Albums matching user's top affinity rank first!)
    final rankedAlbums = List<Album>.from(MockMusicCatalog.topAlbums);
    rankedAlbums.sort((a, b) {
      final aArtist = MockMusicCatalog.normalizeArtistName(a.artist);
      final bArtist = MockMusicCatalog.normalizeArtistName(b.artist);
      final scoreA = (artistAffinity[aArtist] ?? 0) * 10 + a.songs.length;
      final scoreB = (artistAffinity[bArtist] ?? 0) * 10 + b.songs.length;
      return scoreB.compareTo(scoreA);
    });

    // 7. Dynamic Artist Ranking
    final rankedArtists = List<Artist>.from(MockMusicCatalog.popularArtists);
    rankedArtists.sort((a, b) {
      final scoreA = (artistAffinity[a.name] ?? 0) * 10 + a.topTracks.length;
      final scoreB = (artistAffinity[b.name] ?? 0) * 10 + b.topTracks.length;
      return scoreB.compareTo(scoreA);
    });

    // 8. Assemble 100% Authentic Spotify Dynamic Shelves
    final deletedPlaylists = LocalStorageService.getDeletedPlaylistIds();
    final cleanTrendingPlaylists = trendingTamilPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanMadeForYou = madeForYouPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanTimePlaylists = timePlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();

    final List<HomeSection> dynamicSections = [
      if (cleanTrendingPlaylists.isNotEmpty)
        HomeSection(
          id: 'trending_playlists',
          title: 'Trending Now',
          type: HomeSectionType.playlists,
          playlists: cleanTrendingPlaylists,
        ),
      HomeSection(
        id: 'trending_tracks',
        title: 'Today’s Top Hits',
        type: HomeSectionType.songs,
        songs: trendingSongs.take(15).toList(),
      ),
      if (cleanMadeForYou.isNotEmpty)
        HomeSection(
          id: 'made_for_you',
          title: 'Made For You',
          type: HomeSectionType.playlists,
          playlists: cleanMadeForYou,
        ),
      if (rankedAlbums.isNotEmpty)
        HomeSection(
          id: 'new_releases',
          title: 'New Releases',
          type: HomeSectionType.albums,
          albums: rankedAlbums,
        ),
      if (cleanTimePlaylists.isNotEmpty)
        HomeSection(
          id: 'time_mood',
          title: timeSectionTitle,
          type: HomeSectionType.playlists,
          playlists: cleanTimePlaylists,
        ),
      if (rankedArtists.isNotEmpty)
        HomeSection(
          id: 'popular_artists',
          title: 'Popular Artists',
          type: HomeSectionType.artists,
          artists: rankedArtists,
        ),
    ];

    return HomeFeedData(
      greeting: greeting,
      quickPlaySongs: quickPlay,
      aiSpotlight: null,
      sections: dynamicSections,
    );
  }

  int _getSongTrendWeight(Song song) {
    int weight = 50;
    final title = song.title.toLowerCase();
    final movie = (song.movieName ?? song.album).toLowerCase();
    final artist = song.artist.toLowerCase();

    // Top viral songs in current Tamil trend
    if (movie.contains('goat') || movie.contains('greatest')) weight += 100;
    if (movie.contains('amaran')) weight += 95;
    if (movie.contains('vettaiyan')) weight += 90;
    if (movie.contains('leo')) weight += 85;
    if (movie.contains('jailer')) weight += 80;
    if (title.contains('matta') || title.contains('spark') || title.contains('minnale')) weight += 60;
    if (title.contains('hukum') || title.contains('badass') || title.contains('katchi')) weight += 55;
    if (artist.contains('anirudh')) weight += 40;
    if (artist.contains('rahman')) weight += 35;
    if (artist.contains('sai abhyankkar')) weight += 35;
    if (artist.contains('yuvan')) weight += 30;

    return weight;
  }

  /// STRICT ARTIST MIX FILTER: Only returns songs strictly by this artist! Zero unrelated songs.
  List<Song> _getArtistMixTracks(List<Song> allSongs, String artist) {
    return allSongs.where((s) => MockMusicCatalog.isSongByArtist(s, artist)).take(25).toList();
  }
}
