import 'dart:async';
import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../app/constants.dart';
import '../../shared/models/song.dart';
import '../../shared/models/playlist.dart';
import '../../shared/models/album.dart';
import '../../shared/models/artist.dart';
import '../audio/audio_manager.dart';
import '../data/mock_catalog.dart';
import '../storage/local_storage.dart';

enum HomeSectionType {
  playlists,
  albums,
  artists,
  songs,
}

class AiSpotlightData {
  final String title;
  final String rationale;
  final String badge;
  final Song featuredSong;
  final List<Song> playlist;

  AiSpotlightData({
    required this.title,
    required this.rationale,
    required this.badge,
    required this.featuredSong,
    required this.playlist,
  });
}

/// A dynamically computed Home Section (shelf) generated by the recommendation algorithm
class HomeSection {
  final String id;
  final String title;
  final String? subtitle;
  final String? badge;
  final HomeSectionType type;
  final List<Playlist>? playlists;
  final List<Album>? albums;
  final List<Artist>? artists;
  final List<Song>? songs;

  HomeSection({
    required this.id,
    required this.title,
    this.subtitle,
    this.badge,
    required this.type,
    this.playlists,
    this.albums,
    this.artists,
    this.songs,
  });
}

/// A dynamic card item specifically for the top 6-grid on Home page
class QuickPlayCardItem {
  final String id;
  final String title;
  final String imageUrl;
  final Song? song;
  final Album? album;
  final Playlist? playlist;

  QuickPlayCardItem({
    required this.id,
    required this.title,
    required this.imageUrl,
    this.song,
    this.album,
    this.playlist,
  });
}

/// Fully Dynamic Home Feed computed from user behavior & Gemini AI trend analysis
class HomeFeedData {
  final String greeting;
  final List<Song> quickPlaySongs;
  final List<QuickPlayCardItem> quickPlayCards;
  final AiSpotlightData? aiSpotlight;
  final List<HomeSection> sections;

  HomeFeedData({
    required this.greeting,
    required this.quickPlaySongs,
    required this.quickPlayCards,
    this.aiSpotlight,
    required this.sections,
  });
}

final recommendationServiceProvider = Provider<RecommendationService>((ref) {
  return RecommendationService();
});

final homeFeedProvider = StateNotifierProvider<HomeFeedNotifier, AsyncValue<HomeFeedData>>((ref) {
  final service = ref.watch(recommendationServiceProvider);
  return HomeFeedNotifier(service, ref);
});

class HomeFeedNotifier extends StateNotifier<AsyncValue<HomeFeedData>> {
  final RecommendationService _service;
  final Ref _ref;

  HomeFeedNotifier(this._service, this._ref)
      : super(AsyncValue.data(_service.generateLocalAlgorithmicFeed(
          currentSong: _ref.read(playerStateProvider).currentSong ??
              (LocalStorageService.getRecentlyPlayed().isNotEmpty
                  ? LocalStorageService.getRecentlyPlayed().first
                  : null) ??
              LocalStorageService.getLastPlaybackState().song,
        ))) {
    // ⚡ REAL-TIME REACTIVE 6-GRID LISTENER:
    // Whenever user plays or changes a song, immediately update the 6-grid live in 0ms!
    _ref.listen(playerStateProvider.select((s) => s.currentSong?.id), (previous, next) {
      if (next != null && next != previous) {
        _updateFeedImmediate();
      }
    });
  }

  void _updateFeedImmediate() {
    final currentSong = _ref.read(playerStateProvider).currentSong ??
        (LocalStorageService.getRecentlyPlayed().isNotEmpty ? LocalStorageService.getRecentlyPlayed().first : null) ??
        LocalStorageService.getLastPlaybackState().song;
    final feed = _service.generateLocalAlgorithmicFeed(currentSong: currentSong);
    state = AsyncValue.data(feed);
  }

  Future<void> refreshFeed() async {
    _updateFeedImmediate();
  }
}

class RecommendationService {
  final Dio _dio = Dio(BaseOptions(
    connectTimeout: const Duration(milliseconds: 1200),
    receiveTimeout: const Duration(milliseconds: 1200),
  ));

  /// Generates the dynamic algorithmic Home Feed with Gemini AI trend analysis
  Future<HomeFeedData> generateHomeFeed({Song? currentSong}) async {
    // 1. Fetch latest songs from PostgreSQL DB (live sync)
    try {
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final candidateEndpoints = [
        '${AppConstants.defaultApiBaseUrl}/songs?limit=10000&nocache=1&t=$timestamp',
        ...AppConstants.fallbackApiBaseUrls.map((u) => '$u/songs?limit=10000&nocache=1&t=$timestamp'),
      ];

      for (final endpoint in candidateEndpoints) {
        try {
          final songsRes = await _dio.get(endpoint);
          if (songsRes.statusCode == 200 && songsRes.data != null) {
            final data = songsRes.data;
            final list = (data is Map ? (data['data'] ?? data['songs']) : data) as List<dynamic>?;
            if (list != null && list.isNotEmpty) {
              for (final item in list) {
                final songId = (item['id'] ?? '').toString();
                if (songId.isNotEmpty) {
                  final newSong = Song(
                    id: songId,
                    title: (item['title'] ?? 'Untitled Track').toString(),
                    artist: (item['artistName'] ?? item['artist']?['name'] ?? item['artist'] ?? 'Unknown Artist').toString(),
                    album: (item['albumName'] ?? item['album']?['title'] ?? item['album'] ?? 'Single').toString(),
                    movieName: item['movieName']?.toString(),
                    artworkUrl: (item['artworkUrl'] ?? item['artwork'] ?? '').toString(),
                    audioUrl: (item['audioUrl'] ?? '').toString(),
                    duration: (item['duration'] as num?)?.toInt() ?? 180,
                    genre: (item['genre'] ?? 'Music').toString(),
                    language: (item['language'] ?? 'Tamil').toString(),
                    lyrics: (item['lyrics'] is List) ? List<String>.from(item['lyrics']) : [],
                  );
                  MockMusicCatalog.syncSong(newSong);
                }
              }
              break;
            }
          }
        } catch (_) {}
      }
    } catch (_) {}

    final localFeed = generateLocalAlgorithmicFeed(currentSong: currentSong);

    try {
      final res = await _dio.get(
        '${AppConstants.defaultApiBaseUrl}/recommendations/trending',
      );

      if (res.statusCode == 200 && res.data != null) {
        final data = res.data as Map<String, dynamic>;
        final spotlight = data['dailySpotlight'] as Map<String, dynamic>?;
        if (spotlight != null && localFeed.aiSpotlight != null) {
          final updatedSpotlight = AiSpotlightData(
            title: spotlight['title'] ?? localFeed.aiSpotlight!.title,
            rationale: spotlight['rationale'] ?? localFeed.aiSpotlight!.rationale,
            badge: spotlight['badge'] ?? localFeed.aiSpotlight!.badge,
            featuredSong: localFeed.aiSpotlight!.featuredSong,
            playlist: localFeed.aiSpotlight!.playlist,
          );
          return HomeFeedData(
            greeting: localFeed.greeting,
            quickPlaySongs: localFeed.quickPlaySongs,
            quickPlayCards: localFeed.quickPlayCards,
            aiSpotlight: updatedSpotlight,
            sections: localFeed.sections,
          );
        }
      }
    } catch (_) {
      // Offline fallback
    }

    return localFeed;
  }

  /// 100% Dynamic Spotify & Gemini AI Recommendation Engine
  HomeFeedData generateLocalAlgorithmicFeed({Song? currentSong}) {
    final allSongs = MockMusicCatalog.allSongs;
    final recentlyPlayed = LocalStorageService.getRecentlyPlayed();
    final likedSongs = LocalStorageService.getLikedSongs();

    final hour = DateTime.now().hour;
    final String greeting;
    if (hour < 12) {
      greeting = 'Good morning';
    } else if (hour < 17) {
      greeting = 'Good afternoon';
    } else {
      greeting = 'Good evening';
    }

    if (allSongs.isEmpty) {
      return HomeFeedData(
        greeting: greeting,
        quickPlaySongs: [],
        quickPlayCards: [],
        aiSpotlight: null,
        sections: [],
      );
    }

    final lastPlayback = LocalStorageService.getLastPlaybackState();
    final bool isBrandNewUser = recentlyPlayed.isEmpty && likedSongs.isEmpty && currentSong == null && lastPlayback.song == null;

    // --- 6-GRID ALGORITHM: 100% DYNAMIC BEHAVIOR AS REQUESTED ---
    final List<QuickPlayCardItem> quickPlayCards = [];
    final Set<String> usedSongIds = {};

    if (!isBrandNewUser) {
      // 1. Card 1: User's latest / currently listened song
      final Song? card1Song = (currentSong) ??
          (recentlyPlayed.isNotEmpty ? recentlyPlayed.first : null) ??
          (lastPlayback.song) ??
          (allSongs.isNotEmpty ? allSongs.first : null);
    if (card1Song != null) {
      usedSongIds.add(card1Song.id);
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot1_${card1Song.id}',
        title: card1Song.title,
        imageUrl: card1Song.artworkUrl,
        song: card1Song,
      ));
    }

    // 2. Card 2: Previous song from a DIFFERENT movie/album (1st moves to 2nd on new movie play)
    final card1Movie = (card1Song?.movieName ?? card1Song?.album ?? '').trim().toLowerCase();
    
    // First try from recentlyPlayed (a different movie played recently)
    Song? card2Song = recentlyPlayed.where((s) {
      if (usedSongIds.contains(s.id)) return false;
      final m = (s.movieName ?? s.album).trim().toLowerCase();
      return m.isNotEmpty && m != card1Movie;
    }).firstOrNull;

    // Next try from allSongs with a strictly DIFFERENT movie
    card2Song ??= allSongs.where((s) {
      if (usedSongIds.contains(s.id)) return false;
      final m = (s.movieName ?? s.album).trim().toLowerCase();
      return m.isNotEmpty && m != card1Movie;
    }).firstOrNull;

    // Fallback only if entire library has only 1 movie
    card2Song ??= allSongs.where((s) => !usedSongIds.contains(s.id)).firstOrNull;

    if (card2Song != null) {
      usedSongIds.add(card2Song.id);
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot2_${card2Song.id}',
        title: card2Song.title,
        imageUrl: card2Song.artworkUrl,
        song: card2Song,
      ));
    }

    // 3. Card 3: Highly listened song (Most repeated song by user, or top liked song)
    final Map<String, int> songFrequency = {};
    for (final s in recentlyPlayed) {
      songFrequency[s.id] = (songFrequency[s.id] ?? 0) + 1;
    }
    for (final s in likedSongs) {
      songFrequency[s.id] = (songFrequency[s.id] ?? 0) + 3;
    }
    final candidateCard3Songs = allSongs.where((s) => !usedSongIds.contains(s.id)).toList()
      ..sort((a, b) => (songFrequency[b.id] ?? 0).compareTo(songFrequency[a.id] ?? 0));
    
    Song? card3Song = candidateCard3Songs.firstOrNull;
    if (card3Song != null) {
      usedSongIds.add(card3Song.id);
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot3_${card3Song.id}',
        title: card3Song.title,
        imageUrl: card3Song.artworkUrl,
        song: card3Song,
      ));
    }

    // 4. Card 4: Highly listened Album / Movie
    final Map<String, int> albumFrequency = {};
    for (final s in [...recentlyPlayed, ...likedSongs]) {
      final m = (s.movieName ?? s.album).trim();
      if (m.isNotEmpty) {
        albumFrequency[m] = (albumFrequency[m] ?? 0) + 1;
      }
    }
    final sortedUserAlbums = albumFrequency.keys.toList()
      ..sort((a, b) => (albumFrequency[b] ?? 0).compareTo(albumFrequency[a] ?? 0));

    Album? card4Album;
    if (sortedUserAlbums.isNotEmpty) {
      final topName = sortedUserAlbums.first.toLowerCase();
      card4Album = MockMusicCatalog.topAlbums.where((a) => a.title.toLowerCase() == topName).firstOrNull;
    }
    card4Album ??= MockMusicCatalog.topAlbums.firstOrNull;

    if (card4Album != null) {
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot4_album_${card4Album.id}',
        title: card4Album.title,
        imageUrl: card4Album.artworkUrl,
        album: card4Album,
      ));
    } else {
      final s = allSongs.where((x) => !usedSongIds.contains(x.id)).firstOrNull ?? (allSongs.isNotEmpty ? allSongs.first : null);
      if (s != null) {
        usedSongIds.add(s.id);
        quickPlayCards.add(QuickPlayCardItem(
          id: 'slot4_song_${s.id}',
          title: s.movieName ?? s.album,
          imageUrl: s.artworkUrl,
          song: s,
        ));
      }
    }

    // 5. Card 5: Trending song (What users listen to heavily)
    final candidateCard5 = allSongs.where((s) => !usedSongIds.contains(s.id)).toList()
      ..sort((a, b) => _getSongTrendWeight(b, recentlyPlayed, likedSongs).compareTo(_getSongTrendWeight(a, recentlyPlayed, likedSongs)));
    
    Song? card5Trending = candidateCard5.firstOrNull;
    if (card5Trending != null) {
      usedSongIds.add(card5Trending.id);
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot5_${card5Trending.id}',
        title: card5Trending.title,
        imageUrl: card5Trending.artworkUrl,
        song: card5Trending,
      ));
    }

    // 6. Card 6: Playlist (Custom playlist, Liked Songs playlist, or Top Hits Mix / Top Album)
    final customPlaylists = LocalStorageService.getCustomPlaylists();
    final Playlist? card6Playlist = (customPlaylists.isNotEmpty ? customPlaylists.first : null) ??
        (MockMusicCatalog.featuredPlaylists.isNotEmpty ? MockMusicCatalog.featuredPlaylists.first : null);
    
    if (card6Playlist != null) {
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot6_playlist_${card6Playlist.id}',
        title: card6Playlist.title,
        imageUrl: card6Playlist.coverUrl,
        playlist: card6Playlist,
      ));
    } else if (MockMusicCatalog.topAlbums.length > 1 && MockMusicCatalog.topAlbums[1].id != card4Album?.id) {
      final alb = MockMusicCatalog.topAlbums[1];
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot6_album_${alb.id}',
        title: alb.title,
        imageUrl: alb.artworkUrl,
        album: alb,
      ));
    } else {
      final distinctTrack = allSongs.where((s) => !usedSongIds.contains(s.id)).firstOrNull ?? (allSongs.isNotEmpty ? allSongs.last : null);
      quickPlayCards.add(QuickPlayCardItem(
        id: 'slot6_top_hits',
        title: 'Top Hits',
        imageUrl: distinctTrack?.artworkUrl ?? (allSongs.isNotEmpty ? allSongs.first.artworkUrl : ''),
      ));
    }
    }

    final List<Song> quickPlay = quickPlayCards.map((c) => c.song).whereType<Song>().toList();

    // --- 100% DYNAMIC USER AFFINITY & TASTE PROFILE (ZERO HARDCODED NAMES) ---
    final Map<String, int> artistFrequency = {};
    for (final s in recentlyPlayed) {
      final names = MockMusicCatalog.extractArtistsList(s.artist);
      for (final a in names) {
        if (a.isNotEmpty && a.toLowerCase() != 'unknown artist') {
          artistFrequency[a] = (artistFrequency[a] ?? 0) + 3;
        }
      }
    }
    for (final s in likedSongs) {
      final names = MockMusicCatalog.extractArtistsList(s.artist);
      for (final a in names) {
        if (a.isNotEmpty && a.toLowerCase() != 'unknown artist') {
          artistFrequency[a] = (artistFrequency[a] ?? 0) + 2;
        }
      }
    }

    final sortedUserArtists = artistFrequency.keys.toList()
      ..sort((a, b) => (artistFrequency[b] ?? 0).compareTo(artistFrequency[a] ?? 0));

    final dynamicTopArtists = sortedUserArtists.isNotEmpty
        ? sortedUserArtists
        : MockMusicCatalog.popularArtists.map((a) => a.name).toList();

    final top1 = dynamicTopArtists.isNotEmpty ? dynamicTopArtists[0] : '';
    final top2 = dynamicTopArtists.length > 1 ? dynamicTopArtists[1] : '';
    final top3 = dynamicTopArtists.length > 2 ? dynamicTopArtists[2] : '';

    // 2. Curated Dynamic Playlists built strictly from real DB songs & user taste
    final trendingSongs = List<Song>.from(allSongs);
    trendingSongs.sort((a, b) {
      final aTrendWeight = _getSongTrendWeight(a, recentlyPlayed, likedSongs);
      final bTrendWeight = _getSongTrendWeight(b, recentlyPlayed, likedSongs);
      return bTrendWeight.compareTo(aTrendWeight);
    });

    final List<Playlist> trendingTamilPlaylists = [];
    if (trendingSongs.isNotEmpty) {
      trendingTamilPlaylists.add(Playlist(
        id: 'muxiz_top_hits',
        title: 'Top Hits',
        description: 'Most popular tracks from your cloud database.',
        coverUrl: trendingSongs.first.artworkUrl,
        creator: 'Muxiz Editorial',
        songs: trendingSongs.take(20).toList(),
      ));
    }
    if (trendingSongs.length > 3) {
      trendingTamilPlaylists.add(Playlist(
        id: 'fresh_drops',
        title: 'Fresh Drops',
        description: 'Latest additions in your music database.',
        coverUrl: trendingSongs[1].artworkUrl,
        creator: 'Muxiz Database',
        songs: trendingSongs.skip(2).take(15).toList(),
      ));
    }
    for (final artistName in dynamicTopArtists.take(3)) {
      final artistTracks = _getArtistMixTracks(allSongs, artistName);
      if (artistTracks.isNotEmpty) {
        trendingTamilPlaylists.add(Playlist(
          id: 'artist_mix_${artistName.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$artistName Radio',
          description: 'Tracks strictly by $artistName.',
          coverUrl: artistTracks.first.artworkUrl,
          creator: 'Muxiz AI',
          songs: artistTracks,
        ));
      }
    }

    // 4. Dynamic Section: "Made For You" (Strictly tailored to user's listened artists)
    final mix1Songs = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : <Song>[];
    final mix2Songs = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : <Song>[];
    final mix3Songs = top3.isNotEmpty ? _getArtistMixTracks(allSongs, top3) : <Song>[];

    final heardIds = {...recentlyPlayed.map((s) => s.id), ...likedSongs.map((s) => s.id)};
    final discoverSongs = allSongs.where((s) {
      if (heardIds.contains(s.id)) return false;
      return (top1.isNotEmpty && MockMusicCatalog.isSongByArtist(s, top1)) ||
          (top2.isNotEmpty && MockMusicCatalog.isSongByArtist(s, top2)) ||
          (top3.isNotEmpty && MockMusicCatalog.isSongByArtist(s, top3));
    }).take(20).toList();

    final madeForYouPlaylists = [
      if (mix1Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top1.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top1 Mix',
          description: 'The best of $top1, personalized for you.',
          coverUrl: mix1Songs.first.artworkUrl,
          creator: 'Muxiz AI',
          songs: mix1Songs,
        ),
      if (mix2Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top2.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top2 Mix',
          description: 'The best of $top2, personalized for you.',
          coverUrl: mix2Songs.first.artworkUrl,
          creator: 'Muxiz AI',
          songs: mix2Songs,
        ),
      if (mix3Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top3.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top3 Mix',
          description: 'The best of $top3, personalized for you.',
          coverUrl: mix3Songs.first.artworkUrl,
          creator: 'Muxiz AI',
          songs: mix3Songs,
        ),
      if (discoverSongs.isNotEmpty)
        Playlist(
          id: 'discover_weekly',
          title: 'Discover Mix',
          description: 'Fresh tracks picked from your listening preferences.',
          coverUrl: discoverSongs.first.artworkUrl,
          creator: 'Muxiz AI',
          songs: discoverSongs,
        ),
    ];

    // 5. Dynamic Section: Time & Mood Shift Shelf (Derived from user taste & time of day)
    final String timeSectionTitle;
    final List<Playlist> timePlaylists;
    if (hour >= 5 && hour < 12) {
      timeSectionTitle = 'Morning Motivation';
      final morningTracks = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : allSongs.take(15).toList();
      final acousticTracks = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : allSongs.skip(2).take(15).toList();

      timePlaylists = [
        if (morningTracks.isNotEmpty)
          Playlist(
            id: 'morning_energy',
            title: top1.isNotEmpty ? '$top1 Morning' : 'Morning Energy',
            description: 'Uplifting tracks to start your day.',
            coverUrl: morningTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: morningTracks,
          ),
        if (acousticTracks.isNotEmpty)
          Playlist(
            id: 'acoustic_morning',
            title: top2.isNotEmpty ? '$top2 Essentials' : 'Morning Melodies',
            description: 'Soothing tunes for a fresh morning.',
            coverUrl: acousticTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: acousticTracks,
          ),
      ];
    } else if (hour >= 12 && hour < 17) {
      timeSectionTitle = 'Afternoon Beats';
      final afternoonTracks = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : allSongs.take(15).toList();
      final driveTracks = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : allSongs.skip(2).take(15).toList();

      timePlaylists = [
        if (afternoonTracks.isNotEmpty)
          Playlist(
            id: 'afternoon_flow',
            title: top1.isNotEmpty ? '$top1 Flow' : 'Afternoon Flow',
            description: 'High energy tracks from your database.',
            coverUrl: afternoonTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: afternoonTracks,
          ),
        if (driveTracks.isNotEmpty)
          Playlist(
            id: 'drive_beats',
            title: top2.isNotEmpty ? '$top2 Drive' : 'Drive Beats',
            description: 'The ultimate driving soundtrack for your afternoon.',
            coverUrl: driveTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: driveTracks,
          ),
      ];
    } else if (hour >= 17 && hour < 22) {
      timeSectionTitle = 'Evening Melodies';
      final eveningTracks = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : allSongs.take(15).toList();
      final sunsetTracks = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : allSongs.skip(3).take(15).toList();

      timePlaylists = [
        if (eveningTracks.isNotEmpty)
          Playlist(
            id: 'evening_unwind',
            title: top1.isNotEmpty ? '$top1 Evening' : 'Evening Unwind',
            description: 'Relax and groove with iconic melodies.',
            coverUrl: eveningTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: eveningTracks,
          ),
        if (sunsetTracks.isNotEmpty)
          Playlist(
            id: 'sunset_melodies',
            title: top2.isNotEmpty ? '$top2 Sunset' : 'Sunset Melodies',
            description: 'Golden hour melodies and acoustic harmonies.',
            coverUrl: sunsetTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: sunsetTracks,
          ),
      ];
    } else {
      timeSectionTitle = 'Late Night Chill';
      final nightTracks = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : allSongs.take(15).toList();
      final midnightTracks = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : allSongs.skip(2).take(15).toList();

      timePlaylists = [
        if (nightTracks.isNotEmpty)
          Playlist(
            id: 'late_night_chill',
            title: top1.isNotEmpty ? '$top1 Midnight' : 'Late Night Chill',
            description: 'Soft soul vocals & soothing midnight vibes.',
            coverUrl: nightTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: nightTracks,
          ),
        if (midnightTracks.isNotEmpty)
          Playlist(
            id: 'midnight_nostalgia',
            title: top2.isNotEmpty ? '$top2 Night' : 'Midnight Nostalgia',
            description: 'Evergreen night tracks from your library.',
            coverUrl: midnightTracks.first.artworkUrl,
            creator: 'Muxiz AI',
            songs: midnightTracks,
          ),
      ];
    }

    // 6. Dynamic Album Ranking
    final rankedAlbums = List<Album>.from(MockMusicCatalog.topAlbums);

    // 7. Dynamic Artist Ranking
    final rankedArtists = List<Artist>.from(MockMusicCatalog.popularArtists);

    // 8. Assemble Dynamic Shelves
    final deletedPlaylists = LocalStorageService.getDeletedPlaylistIds();
    final cleanTrendingPlaylists = trendingTamilPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanMadeForYou = madeForYouPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanTimePlaylists = timePlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();

    final List<HomeSection> dynamicSections = [
      if (cleanTrendingPlaylists.isNotEmpty)
        HomeSection(
          id: 'trending_playlists',
          title: 'Trending Now',
          type: HomeSectionType.playlists,
          playlists: cleanTrendingPlaylists,
        ),
      HomeSection(
        id: 'trending_tracks',
        title: 'Today’s Top Hits',
        type: HomeSectionType.songs,
        songs: trendingSongs.take(15).toList(),
      ),
      if (cleanMadeForYou.isNotEmpty)
        HomeSection(
          id: 'made_for_you',
          title: 'Made For You',
          type: HomeSectionType.playlists,
          playlists: cleanMadeForYou,
        ),
      if (rankedAlbums.isNotEmpty)
        HomeSection(
          id: 'new_releases',
          title: 'New Releases',
          type: HomeSectionType.albums,
          albums: rankedAlbums,
        ),
      if (cleanTimePlaylists.isNotEmpty)
        HomeSection(
          id: 'time_mood',
          title: timeSectionTitle,
          type: HomeSectionType.playlists,
          playlists: cleanTimePlaylists,
        ),
      if (rankedArtists.isNotEmpty)
        HomeSection(
          id: 'popular_artists',
          title: 'Popular Artists',
          type: HomeSectionType.artists,
          artists: rankedArtists,
        ),
    ];

    return HomeFeedData(
      greeting: greeting,
      quickPlaySongs: quickPlay,
      quickPlayCards: quickPlayCards,
      aiSpotlight: null,
      sections: dynamicSections,
    );
  }

  /// 100% Dynamic User Affinity Scoring (Zero Hardcoded Strings)
  int _getSongTrendWeight(Song song, List<Song> recentlyPlayed, List<Song> likedSongs) {
    int weight = 50;

    // 1. User Liked Song Boost
    final isLiked = likedSongs.any((s) => s.id == song.id);
    if (isLiked) weight += 60;

    // 2. User Play Frequency Boost (tracks listened more often rank higher)
    final playCount = recentlyPlayed.where((s) => s.id == song.id).length;
    weight += playCount * 30;

    // 3. User Favorite Artist Boost (dynamically matches artists the user actually listens to)
    final isUserArtist = recentlyPlayed.any((s) => MockMusicCatalog.isSongByArtist(song, s.artist));
    if (isUserArtist) weight += 35;

    // 4. User Favorite Movie/Album Boost
    final songMovie = (song.movieName ?? song.album).trim().toLowerCase();
    if (songMovie.isNotEmpty) {
      final isUserMovie = recentlyPlayed.any((s) => (s.movieName ?? s.album).trim().toLowerCase() == songMovie);
      if (isUserMovie) weight += 25;
    }

    return weight;
  }

  /// STRICT ARTIST MIX FILTER: Only returns songs strictly by this artist! Zero unrelated songs.
  List<Song> _getArtistMixTracks(List<Song> allSongs, String artist) {
    return allSongs.where((s) => MockMusicCatalog.isSongByArtist(s, artist)).take(25).toList();
  }
}
