import 'dart:async';
import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../app/constants.dart';
import '../../shared/models/song.dart';
import '../../shared/models/playlist.dart';
import '../../shared/models/album.dart';
import '../../shared/models/artist.dart';
import '../audio/audio_manager.dart';
import '../data/mock_catalog.dart';
import '../network/network_state.dart';
import '../storage/local_storage.dart';

enum HomeSectionType {
  playlists,
  albums,
  artists,
  songs,
}

class AiSpotlightData {
  final String title;
  final String rationale;
  final String badge;
  final Song featuredSong;
  final List<Song> playlist;

  AiSpotlightData({
    required this.title,
    required this.rationale,
    required this.badge,
    required this.featuredSong,
    required this.playlist,
  });
}

/// A dynamically computed Home Section (shelf) generated by the recommendation algorithm
class HomeSection {
  final String id;
  final String title;
  final String? subtitle;
  final String? badge;
  final HomeSectionType type;
  final List<Playlist>? playlists;
  final List<Album>? albums;
  final List<Artist>? artists;
  final List<Song>? songs;

  HomeSection({
    required this.id,
    required this.title,
    this.subtitle,
    this.badge,
    required this.type,
    this.playlists,
    this.albums,
    this.artists,
    this.songs,
  });
}

/// Fully Dynamic Home Feed computed from user behavior & Gemini AI trend analysis
class HomeFeedData {
  final String greeting;
  final List<Song> quickPlaySongs;
  final AiSpotlightData? aiSpotlight;
  final List<HomeSection> sections;

  HomeFeedData({
    required this.greeting,
    required this.quickPlaySongs,
    this.aiSpotlight,
    required this.sections,
  });
}

final recommendationServiceProvider = Provider<RecommendationService>((ref) {
  return RecommendationService();
});

final homeFeedProvider = StateNotifierProvider<HomeFeedNotifier, AsyncValue<HomeFeedData>>((ref) {
  final service = ref.watch(recommendationServiceProvider);
  return HomeFeedNotifier(service, ref);
});

class HomeFeedNotifier extends StateNotifier<AsyncValue<HomeFeedData>> {
  final RecommendationService _service;
  final Ref _ref;
  DateTime? _lastGeneratedTime;
  Timer? _dailyCycleTimer;

  HomeFeedNotifier(this._service, this._ref) : super(const AsyncValue.loading()) {
    refreshFeed();

    // 1. Network reconnection trigger: When internet comes back ON, refresh daily data
    _ref.listen(networkStatusProvider, (previous, next) {
      if (next == NetworkStatus.online && previous != NetworkStatus.online) {
        refreshFeed();
      }
    });

    // 2. Daily 5:30 AM IST timer check (runs every minute to catch 5:30 AM IST boundary while app is open)
    _dailyCycleTimer = Timer.periodic(const Duration(minutes: 1), (_) {
      final mostRecent530Am = _getMostRecent530AmIst();
      if (_lastGeneratedTime != null && _lastGeneratedTime!.isBefore(mostRecent530Am)) {
        refreshFeed();
      }
    });
  }

  /// Calculates the most recent 5:30 AM IST timestamp (UTC 00:00)
  static DateTime _getMostRecent530AmIst() {
    final nowUtc = DateTime.now().toUtc();
    final today530AmIst = DateTime.utc(nowUtc.year, nowUtc.month, nowUtc.day, 0, 0, 0);
    if (nowUtc.isBefore(today530AmIst)) {
      return today530AmIst.subtract(const Duration(days: 1));
    }
    return today530AmIst;
  }

  Future<void> refreshFeed() async {
    try {
      final currentSong = _ref.read(playerStateProvider).currentSong;
      final feed = await _service.generateHomeFeed(currentSong: currentSong);
      _lastGeneratedTime = DateTime.now().toUtc();
      state = AsyncValue.data(feed);
    } catch (e) {
      final currentSong = _ref.read(playerStateProvider).currentSong;
      final fallback = _service.generateLocalAlgorithmicFeed(currentSong: currentSong);
      _lastGeneratedTime = DateTime.now().toUtc();
      state = AsyncValue.data(fallback);
    }
  }

  @override
  void dispose() {
    _dailyCycleTimer?.cancel();
    super.dispose();
  }
}

class RecommendationService {
  final Dio _dio = Dio(BaseOptions(
    connectTimeout: const Duration(milliseconds: 1200),
    receiveTimeout: const Duration(milliseconds: 1200),
  ));

  /// Generates the dynamic algorithmic Home Feed with Gemini AI trend analysis
  Future<HomeFeedData> generateHomeFeed({Song? currentSong}) async {
    // 1. Fetch latest songs from PostgreSQL DB (live sync)
    try {
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final candidateEndpoints = [
        '${AppConstants.defaultApiBaseUrl}/songs?limit=10000&nocache=1&t=$timestamp',
        ...AppConstants.fallbackApiBaseUrls.map((u) => '$u/songs?limit=10000&nocache=1&t=$timestamp'),
      ];

      for (final endpoint in candidateEndpoints) {
        try {
          final songsRes = await _dio.get(endpoint);
          if (songsRes.statusCode == 200 && songsRes.data != null) {
            final data = songsRes.data;
            final list = (data is Map ? (data['data'] ?? data['songs']) : data) as List<dynamic>?;
            if (list != null && list.isNotEmpty) {
              for (final item in list) {
                final songId = (item['id'] ?? '').toString();
                if (songId.isNotEmpty) {
                  final newSong = Song(
                    id: songId,
                    title: (item['title'] ?? 'Untitled Track').toString(),
                    artist: (item['artistName'] ?? item['artist']?['name'] ?? item['artist'] ?? 'Unknown Artist').toString(),
                    album: (item['albumName'] ?? item['album']?['title'] ?? item['album'] ?? 'Single').toString(),
                    movieName: item['movieName']?.toString(),
                    artworkUrl: (item['artworkUrl'] ?? item['artwork'] ?? '').toString(),
                    audioUrl: (item['audioUrl'] ?? '').toString(),
                    duration: (item['duration'] as num?)?.toInt() ?? 180,
                    genre: (item['genre'] ?? 'Music').toString(),
                    language: (item['language'] ?? 'Tamil').toString(),
                    lyrics: (item['lyrics'] is List) ? List<String>.from(item['lyrics']) : [],
                  );
                  MockMusicCatalog.syncSong(newSong);
                }
              }
              break;
            }
          }
        } catch (_) {}
      }
    } catch (_) {}

    final localFeed = generateLocalAlgorithmicFeed(currentSong: currentSong);

    try {
      final res = await _dio.get(
        '${AppConstants.defaultApiBaseUrl}/recommendations/trending',
      );

      if (res.statusCode == 200 && res.data != null) {
        final data = res.data as Map<String, dynamic>;
        final spotlight = data['dailySpotlight'] as Map<String, dynamic>?;
        if (spotlight != null && localFeed.aiSpotlight != null) {
          final updatedSpotlight = AiSpotlightData(
            title: spotlight['title'] ?? localFeed.aiSpotlight!.title,
            rationale: spotlight['rationale'] ?? localFeed.aiSpotlight!.rationale,
            badge: spotlight['badge'] ?? localFeed.aiSpotlight!.badge,
            featuredSong: localFeed.aiSpotlight!.featuredSong,
            playlist: localFeed.aiSpotlight!.playlist,
          );
          return HomeFeedData(
            greeting: localFeed.greeting,
            quickPlaySongs: localFeed.quickPlaySongs,
            aiSpotlight: updatedSpotlight,
            sections: localFeed.sections,
          );
        }
      }
    } catch (_) {
      // Offline fallback
    }

    return localFeed;
  }

  /// 100% Dynamic Spotify & Gemini AI Recommendation Engine
  HomeFeedData generateLocalAlgorithmicFeed({Song? currentSong}) {
    final allSongs = MockMusicCatalog.allSongs;
    final recentlyPlayed = LocalStorageService.getRecentlyPlayed();
    final likedSongs = LocalStorageService.getLikedSongs();

    final hour = DateTime.now().hour;
    final String greeting;
    if (hour < 12) {
      greeting = 'Good morning';
    } else if (hour < 17) {
      greeting = 'Good afternoon';
    } else {
      greeting = 'Good evening';
    }

    if (allSongs.isEmpty) {
      return HomeFeedData(
        greeting: greeting,
        quickPlaySongs: [],
        aiSpotlight: null,
        sections: [],
      );
    }

    // 1. Stable Quick-Play 6 Cards (Fixed catalog order, never shifts upon playback)
    final List<Song> quickPlay = allSongs.take(6).toList();

    // 2. Curated Dynamic Playlists built strictly from real DB songs
    final trendingSongs = List<Song>.from(allSongs);
    trendingSongs.sort((a, b) {
      final aTrendWeight = _getSongTrendWeight(a);
      final bTrendWeight = _getSongTrendWeight(b);
      return bTrendWeight.compareTo(aTrendWeight);
    });

    // Curated Dynamic Playlists built strictly from real DB songs
    final List<Playlist> trendingTamilPlaylists = [];
    if (trendingSongs.isNotEmpty) {
      trendingTamilPlaylists.add(Playlist(
        id: 'muxiz_top_hits',
        title: 'Top Hits',
        description: 'Most popular tracks from your cloud database.',
        coverUrl: trendingSongs.first.artworkUrl,
        creator: 'Muxiz Editorial',
        songs: trendingSongs.take(20).toList(),
      ));
    }
    if (trendingSongs.length > 3) {
      trendingTamilPlaylists.add(Playlist(
        id: 'fresh_drops',
        title: 'Fresh Drops',
        description: 'Latest additions in your music database.',
        coverUrl: trendingSongs[1].artworkUrl,
        creator: 'Muxiz Database',
        songs: trendingSongs.skip(2).take(15).toList(),
      ));
    }
    for (final artist in MockMusicCatalog.popularArtists.take(3)) {
      if (artist.topTracks.isNotEmpty) {
        trendingTamilPlaylists.add(Playlist(
          id: 'artist_mix_${artist.id}',
          title: '${artist.name} Radio',
          description: 'Tracks strictly by ${artist.name}.',
          coverUrl: artist.imageUrl,
          creator: 'Muxiz AI',
          songs: artist.topTracks,
        ));
      }
    }

    final topArtists = MockMusicCatalog.popularArtists.map((a) => a.name).toList();
    final top1 = topArtists.isNotEmpty ? topArtists[0] : '';
    final top2 = topArtists.length > 1 ? topArtists[1] : '';
    final top3 = topArtists.length > 2 ? topArtists[2] : '';

    // 4. Dynamic Section: "Made For You" (Strictly ONLY songs by each specific artist)
    final mix1Songs = top1.isNotEmpty ? _getArtistMixTracks(allSongs, top1) : <Song>[];
    final mix2Songs = top2.isNotEmpty ? _getArtistMixTracks(allSongs, top2) : <Song>[];
    final mix3Songs = top3.isNotEmpty ? _getArtistMixTracks(allSongs, top3) : <Song>[];

    final heardIds = {...recentlyPlayed.map((s) => s.id), ...likedSongs.map((s) => s.id)};
    final discoverSongs = allSongs.where((s) {
      if (heardIds.contains(s.id)) return false;
      return MockMusicCatalog.isSongByArtist(s, top1) ||
          MockMusicCatalog.isSongByArtist(s, top2) ||
          MockMusicCatalog.isSongByArtist(s, top3);
    }).take(20).toList();

    final madeForYouPlaylists = [
      if (mix1Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top1.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top1 Mix',
          description: 'The best of $top1, all in one place.',
          coverUrl: mix1Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix1Songs,
        ),
      if (mix2Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top2.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top2 Mix',
          description: 'The best of $top2, all in one place.',
          coverUrl: mix2Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix2Songs,
        ),
      if (mix3Songs.isNotEmpty)
        Playlist(
          id: 'mix_${top3.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}',
          title: '$top3 Mix',
          description: 'The best of $top3, all in one place.',
          coverUrl: mix3Songs.first.artworkUrl,
          creator: 'Spotify',
          songs: mix3Songs,
        ),
      if (discoverSongs.isNotEmpty)
        Playlist(
          id: 'discover_weekly',
          title: 'Discover Weekly',
          description: 'Your weekly mixtape of fresh tracks picked for you.',
          coverUrl: discoverSongs.first.artworkUrl,
          creator: 'Spotify',
          songs: discoverSongs,
        ),
    ];

    // 5. Dynamic Section: Time & Mood Shift Shelf (Strict thematic songs only)
    final String timeSectionTitle;
    final List<Playlist> timePlaylists;
    if (hour >= 5 && hour < 12) {
      timeSectionTitle = 'Morning Motivation';
      final morningMotivation = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return a.contains('anirudh') ||
            a.contains('santhosh') ||
            a.contains('hiphop') ||
            t.contains('arambam') ||
            t.contains('rise') ||
            t.contains('power') ||
            t.contains('badass') ||
            t.contains('energy');
      }).take(15).toList();

      final acousticMorning = allSongs.where((s) {
        final t = s.title.toLowerCase();
        final a = s.artist.toLowerCase();
        return t.contains('kadhal') ||
            t.contains('melody') ||
            t.contains('kanave') ||
            t.contains('poo') ||
            a.contains('sid sriram') ||
            a.contains('pradeep kumar');
      }).take(15).toList();

      timePlaylists = [
        if (morningMotivation.isNotEmpty)
          Playlist(
            id: 'morning_energy',
            title: 'Morning Motivation',
            description: 'Uplifting tracks to start your day with power.',
            coverUrl: morningMotivation.first.artworkUrl,
            creator: 'Spotify',
            songs: morningMotivation,
          ),
        if (acousticMorning.isNotEmpty)
          Playlist(
            id: 'acoustic_morning',
            title: 'Tamil Acoustic Starts',
            description: 'Soothing morning acoustic guitar and vocals.',
            coverUrl: acousticMorning.first.artworkUrl,
            creator: 'Spotify',
            songs: acousticMorning,
          ),
      ];
    } else if (hour >= 12 && hour < 17) {
      timeSectionTitle = 'Afternoon Beats';
      final partyHits = allSongs.take(15).toList();
      final driveHits = allSongs.skip(2).take(15).toList();

      timePlaylists = [
        if (partyHits.isNotEmpty)
          Playlist(
            id: 'afternoon_flow',
            title: 'Afternoon Flow',
            description: 'High energy tracks from your database.',
            coverUrl: partyHits.first.artworkUrl,
            creator: 'Muxiz',
            songs: partyHits,
          ),
        if (driveHits.isNotEmpty)
          Playlist(
            id: 'kollywood_drive',
            title: 'Drive Beats',
            description: 'The ultimate driving soundtrack for your afternoon.',
            coverUrl: driveHits.first.artworkUrl,
            creator: 'Muxiz',
            songs: driveHits,
          ),
      ];
    } else if (hour >= 17 && hour < 22) {
      timeSectionTitle = 'Evening Melodies';
      final eveningUnwind = allSongs.take(15).toList();
      final sunsetMelodies = allSongs.skip(3).take(15).toList();

      timePlaylists = [
        if (eveningUnwind.isNotEmpty)
          Playlist(
            id: 'evening_unwind',
            title: 'Evening Unwind',
            description: 'Relax and groove with iconic melodies from your vault.',
            coverUrl: eveningUnwind.first.artworkUrl,
            creator: 'Muxiz',
            songs: eveningUnwind,
          ),
        if (sunsetMelodies.isNotEmpty)
          Playlist(
            id: 'sunset_melodies',
            title: 'Sunset Melodies',
            description: 'Golden hour melodies and acoustic harmonies.',
            coverUrl: sunsetMelodies.first.artworkUrl,
            creator: 'Muxiz',
            songs: sunsetMelodies,
          ),
      ];
    } else {
      timeSectionTitle = 'Late Night Chill';
      final lateNightMelodies = allSongs.take(15).toList();
      final midnightNostalgia = allSongs.skip(2).take(15).toList();

      timePlaylists = [
        if (lateNightMelodies.isNotEmpty)
          Playlist(
            id: 'late_night_chill',
            title: 'Late Night Chill',
            description: 'Soft soul vocals & soothing midnight vibes from your vault.',
            coverUrl: lateNightMelodies.first.artworkUrl,
            creator: 'Muxiz',
            songs: lateNightMelodies,
          ),
        if (midnightNostalgia.isNotEmpty)
          Playlist(
            id: 'midnight_nostalgia',
            title: 'Midnight Nostalgia',
            description: 'Evergreen night tracks from your library.',
            coverUrl: midnightNostalgia.first.artworkUrl,
            creator: 'Muxiz',
            songs: midnightNostalgia,
          ),
      ];
    }

    // 6. Dynamic Album Ranking
    final rankedAlbums = List<Album>.from(MockMusicCatalog.topAlbums);

    // 7. Dynamic Artist Ranking
    final rankedArtists = List<Artist>.from(MockMusicCatalog.popularArtists);

    // 8. Assemble 100% Authentic Spotify Dynamic Shelves
    final deletedPlaylists = LocalStorageService.getDeletedPlaylistIds();
    final cleanTrendingPlaylists = trendingTamilPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanMadeForYou = madeForYouPlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();
    final cleanTimePlaylists = timePlaylists.where((p) => !deletedPlaylists.contains(p.id)).toList();

    final List<HomeSection> dynamicSections = [
      if (cleanTrendingPlaylists.isNotEmpty)
        HomeSection(
          id: 'trending_playlists',
          title: 'Trending Now',
          type: HomeSectionType.playlists,
          playlists: cleanTrendingPlaylists,
        ),
      HomeSection(
        id: 'trending_tracks',
        title: 'Today’s Top Hits',
        type: HomeSectionType.songs,
        songs: trendingSongs.take(15).toList(),
      ),
      if (cleanMadeForYou.isNotEmpty)
        HomeSection(
          id: 'made_for_you',
          title: 'Made For You',
          type: HomeSectionType.playlists,
          playlists: cleanMadeForYou,
        ),
      if (rankedAlbums.isNotEmpty)
        HomeSection(
          id: 'new_releases',
          title: 'New Releases',
          type: HomeSectionType.albums,
          albums: rankedAlbums,
        ),
      if (cleanTimePlaylists.isNotEmpty)
        HomeSection(
          id: 'time_mood',
          title: timeSectionTitle,
          type: HomeSectionType.playlists,
          playlists: cleanTimePlaylists,
        ),
      if (rankedArtists.isNotEmpty)
        HomeSection(
          id: 'popular_artists',
          title: 'Popular Artists',
          type: HomeSectionType.artists,
          artists: rankedArtists,
        ),
    ];

    return HomeFeedData(
      greeting: greeting,
      quickPlaySongs: quickPlay,
      aiSpotlight: null,
      sections: dynamicSections,
    );
  }

  int _getSongTrendWeight(Song song) {
    int weight = 50;
    final title = song.title.toLowerCase();
    final movie = (song.movieName ?? song.album).toLowerCase();
    final artist = song.artist.toLowerCase();

    // Top viral songs in current Tamil trend
    if (movie.contains('goat') || movie.contains('greatest')) weight += 100;
    if (movie.contains('amaran')) weight += 95;
    if (movie.contains('vettaiyan')) weight += 90;
    if (movie.contains('leo')) weight += 85;
    if (movie.contains('jailer')) weight += 80;
    if (title.contains('matta') || title.contains('spark') || title.contains('minnale')) weight += 60;
    if (title.contains('hukum') || title.contains('badass') || title.contains('katchi')) weight += 55;
    if (artist.contains('anirudh')) weight += 40;
    if (artist.contains('rahman')) weight += 35;
    if (artist.contains('sai abhyankkar')) weight += 35;
    if (artist.contains('yuvan')) weight += 30;

    return weight;
  }

  /// STRICT ARTIST MIX FILTER: Only returns songs strictly by this artist! Zero unrelated songs.
  List<Song> _getArtistMixTracks(List<Song> allSongs, String artist) {
    return allSongs.where((s) => MockMusicCatalog.isSongByArtist(s, artist)).take(25).toList();
  }
}
