// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2GucILtbjSuRq_ujk8jNMuGw8VBL9Hm4',
    appId: '1:375632972665:web:8744cd941d87da570b3da8',
    messagingSenderId: '375632972665',
    projectId: 'muxiz-app',
    authDomain: 'muxiz-app.firebaseapp.com',
    storageBucket: 'muxiz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2GucILtbjSuRq_ujk8jNMuGw8VBL9Hm4',
    appId: '1:375632972665:android:1644f9019f8bc07c0b3da8',
    messagingSenderId: '375632972665',
    projectId: 'muxiz-app',
    storageBucket: 'muxiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8jowPnp4T4WQ8-KFnBjXEt4b8_oKF7E8',
    appId: '1:375632972665:ios:bdd625bc023bce600b3da8',
    messagingSenderId: '375632972665',
    projectId: 'muxiz-app',
    storageBucket: 'muxiz-app.firebasestorage.app',
    iosClientId: '375632972665-jv2q696l7cmu37germ98obk1raresgvb.apps.googleusercontent.com',
    iosBundleId: 'com.muxiz.app.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8jowPnp4T4WQ8-KFnBjXEt4b8_oKF7E8',
    appId: '1:375632972665:ios:bdd625bc023bce600b3da8',
    messagingSenderId: '375632972665',
    projectId: 'muxiz-app',
    storageBucket: 'muxiz-app.firebasestorage.app',
    iosClientId: '375632972665-jv2q696l7cmu37germ98obk1raresgvb.apps.googleusercontent.com',
    iosBundleId: 'com.muxiz.app.mobile',
  );
}
